[package]
name = "kemuler-enigo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kemuler = { git = "https://github.com/kemuler/kemuler" }
enigo = "0.1.2"
